// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2jylQ5BwMEXMyY5w7ZJFHG4Fzq3obvg',
    appId: '1:939992324681:android:60967050854afe2b8d3d98',
    messagingSenderId: '939992324681',
    projectId: 'clubconnect-17ec5',
    storageBucket: 'clubconnect-17ec5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpy-0BMjeebx6FSYwpuHoyKSklnupokQ',
    appId: '1:939992324681:web:3c5407a6f40ab1678d3d98',
    messagingSenderId: '939992324681',
    projectId: 'clubconnect-17ec5',
    authDomain: 'clubconnect-17ec5.firebaseapp.com',
    storageBucket: 'clubconnect-17ec5.firebasestorage.app',
    measurementId: 'G-8951X6VFKC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEdNZwYud7cCBd52L4M52I2Aot4dns4rg',
    appId: '1:939992324681:ios:9ae0b57d163b764c8d3d98',
    messagingSenderId: '939992324681',
    projectId: 'clubconnect-17ec5',
    storageBucket: 'clubconnect-17ec5.firebasestorage.app',
    iosClientId: '939992324681-5m7ffs58tfgm4b1n38e38q19e5nutmrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.csc234Clubconnect',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdNZwYud7cCBd52L4M52I2Aot4dns4rg',
    appId: '1:939992324681:ios:9ae0b57d163b764c8d3d98',
    messagingSenderId: '939992324681',
    projectId: 'clubconnect-17ec5',
    storageBucket: 'clubconnect-17ec5.firebasestorage.app',
    iosClientId: '939992324681-5m7ffs58tfgm4b1n38e38q19e5nutmrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.csc234Clubconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvpy-0BMjeebx6FSYwpuHoyKSklnupokQ',
    appId: '1:939992324681:web:787f9448d89848e68d3d98',
    messagingSenderId: '939992324681',
    projectId: 'clubconnect-17ec5',
    authDomain: 'clubconnect-17ec5.firebaseapp.com',
    storageBucket: 'clubconnect-17ec5.firebasestorage.app',
    measurementId: 'G-J40ECNS054',
  );

}